export const appConfig = {
  name: "ImpactFlow Web",
  description: "Frontend application for the ImpactFlow Protocol built with Next.js, TypeScript, and Tailwind CSS.",
  structure: [
    "src/app/",
    "src/components/",
    "src/features/",
    "src/services/",
    "src/hooks/",
    "src/store/",
    "src/utils/",
  ],
  features: [
    "Wallet authentication",
    "Funding campaign creation",
    "Beneficiary onboarding",
    "Milestone tracking",
    "DAO governance participation",
    "Transparency dashboard",
    "Real-time funding updates",
  ],
  techStack: [
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "Stellar Wallet Kit",
    "Zustand",
    "React Query",
  ],
};
